import type { Metadata } from "next";
import Link from "next/link";
import {
  DEFAULT_OG_IMAGE,
  DEFAULT_TWITTER_IMAGE,
  SITE_URL,
} from "../lib/site";

export const metadata: Metadata = {
  title: "How Scores Are Calculated | Gud For Us",
  description:
    "Learn how Gud For Us health scores are generated using Google Gemini AI, community product databases, barcode lookups, and live web search.",
  alternates: {
    canonical: `${SITE_URL}/how-scores-are-calculated`,
  },
  openGraph: {
    title: "How Scores Are Calculated | Gud For Us",
    description:
      "Understand how health scores are generated from product data, AI analysis, and web search.",
    url: `${SITE_URL}/how-scores-are-calculated`,
    type: "article",
    images: [{ url: DEFAULT_OG_IMAGE }],
  },
  twitter: {
    card: "summary_large_image",
    title: "How Scores Are Calculated | Gud For Us",
    description:
      "Understand how health scores are generated from product data, AI analysis, and web search.",
    images: [DEFAULT_TWITTER_IMAGE],
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function HowScoresAreCalculatedPage() {
  return (
    <main className="min-h-screen bg-[#fafaf7] text-[#1a1a17] selection:bg-[#d8f3dc] selection:text-[#1a1a17]">
      <section className="relative overflow-hidden px-6 pb-18 pt-[132px]">
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            background:
              "radial-gradient(ellipse 55% 45% at 50% 0%, rgba(45,106,79,0.08) 0%, transparent 72%), radial-gradient(ellipse 35% 35% at 92% 12%, rgba(82,183,136,0.08) 0%, transparent 62%)",
          }}
        />
        <div className="relative mx-auto max-w-5xl">
          <div className="inline-flex items-center gap-2 rounded-full bg-[#d8f3dc] px-4 py-2 text-[0.78rem] font-semibold uppercase tracking-[0.08em] text-[#2d6a4f] shadow-sm">
            <span className="h-2 w-2 rounded-full bg-[#52b788]" />
            Score Transparency
          </div>
          <h1 className="mt-6 max-w-4xl font-display text-[clamp(2.6rem,5.5vw,4.8rem)] leading-[1.03] tracking-[-0.03em] text-[#1a1a17]">
            How scores are calculated
          </h1>
          <p className="mt-6 max-w-3xl text-[1.12rem] leading-[1.8] text-[#5c5c52]">
            We believe health scores should be interpretable, not opaque. This
            page explains the data sources and analysis flow used to generate
            your result.
          </p>
          <div className="mt-10 flex flex-wrap gap-4">
            <Link
              href="/"
              className="inline-flex items-center rounded-full bg-[#2d6a4f] px-7 py-3.5 text-sm font-semibold text-white transition hover:-translate-y-[1px] hover:bg-[#40916c]"
            >
              Try Gud For Us
            </Link>
            
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-24">
        <article className="rounded-[28px] border border-[#edecea] bg-white p-8 shadow-[0_12px_40px_rgba(26,26,23,0.04)] md:p-10">
          <div className="rounded-[24px] border border-[#e8efe8] bg-[#f6fbf7] p-6">
            <p className="text-[0.8rem] font-semibold uppercase tracking-[0.12em] text-[#2d6a4f]">
              How the scoring pipeline works
            </p>
            <p className="mt-3 text-[1.02rem] leading-8 text-[#394138]">
              Health scores are generated by Google Gemini AI using product
              data from open community databases and live web search.
            </p>
          </div>

          <div className="mt-10 space-y-6 text-[1.03rem] leading-8 text-[#3f3f36]">
            <p>
              When a barcode is detected, product information is sourced from
              Open Food Facts, Open Beauty Facts, or UPCitemdb.
            </p>
            <p>
              The AI then analyses ingredients, nutrition, and compatibility
              with your personal profile. Results are further refined using web
              search to improve accuracy.
            </p>
          </div>

          <section className="mt-12 rounded-[24px] border border-[#edecea] bg-[#fcfbf7] p-6">
            <h2 className="font-display text-2xl tracking-tight text-[#1a1a17]">
              Community databases
            </h2>
            <ul className="mt-4 list-disc space-y-2 pl-5 text-[0.98rem] leading-7 text-[#4f4f46]">
              <li>
                <a
                  href="https://world.openfoodfacts.org"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline decoration-[#b7d8c8] underline-offset-4 transition hover:text-[#2d6a4f] hover:decoration-[#2d6a4f]"
                >
                  Open Food Facts - Food & Nutrition Database
                </a>
              </li>
              <li>
                <a
                  href="https://world.openbeautyfacts.org"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline decoration-[#b7d8c8] underline-offset-4 transition hover:text-[#2d6a4f] hover:decoration-[#2d6a4f]"
                >
                  Open Beauty Facts - Cosmetic Ingredient Database
                </a>
              </li>
              <li>
                <a
                  href="https://www.upcitemdb.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline decoration-[#b7d8c8] underline-offset-4 transition hover:text-[#2d6a4f] hover:decoration-[#2d6a4f]"
                >
                  UPCitemdb - Product Information Database
                </a>
              </li>
            </ul>
          </section>

          <section className="mt-8 rounded-[20px] border border-[#f2d5cf] bg-[#fff3f0] p-5">
            <p className="text-[0.96rem] leading-7 text-[#7a2e23]">
              For informational purposes only. Scores are AI-generated and have
              not been clinically validated. Always consult a doctor or
              qualified health professional before making medical or dietary
              decisions.
            </p>
          </section>
        </article>
      </section>
    </main>
  );
}
